# Site settings
title: knoxzin1
email: knoxzin1@gmail.com
description: > # this means to ignore newlines until "baseurl:"

permalink: :title
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://knoxzin1.github.io" # the base hostname & protocol for your site
github_username:  knoxzin1

# Build settings
markdown: kramdown
